#!/usr/bin/env python3
import argparse

def create(name, destination):
    print('hello', name, 'bye', destination)

def main():
    parser = argparse.ArgumentParser(description='Create a Web App!')
    parser.add_argument('name', help='Name of the to-be-created app')
    parser.add_argument('destination', default='.', help='Destination to create app')
    params = parser.parse_args()
    create(params.name, params.destination)
    

if __name__ == '__main__':
    main()